---
title: "The project itself"
author: "Nuno Agostinho"
date: "`r Sys.Date()`"
output: 
  html_document: 
    toc: yes
---

Another thing I have considered is that maybe it'd be best if we used always the
same name for functions belonging to different modules but that doesn't work in
R since each function needs to have its own different name. Another way we maybe
could  accomplish this is by using classes instead. Maybe two methods with the
same name in different classes are allowed? They are definitely allowed in
different environments (creating a list of environments is currently the way I
deal with them).

## Reading data
Reading data should be as fast as possible.
There are two packages that are very fast loading files: `readr` and
`data.table`.

Compared to fread, readr:
* is ~1.2-2x slower. For best performance, use data.table::fread()
* readr has a slightly more sophisticated parser, recognising both doubled
("""") and backslash escapes ("""); readr allows to read factors and date times
directly from disk
* fread() automatically guesses the delimiter, header, lines to skip by default
and more; readr asks for these
* readr is designed to be general, and dealing with new types of rectangular
data just requires implementing a new tokenizer; fread() is designed to be as
fast as possible; fread() is pure C, readr is C++ and Rcpp

Using readr to load a big junction quantification file from BLCA Firehose
cohort took 30 seconds vs fread's 13 seconds.

# R CMD check

## Building error due to the file order
When building a package, R goes through all the files alphabetically. Unless
explicitely stated, you'll get an error if there are unloaded dependencies. To
overcome these, I found four solutions:

* "Collate" field in the DESCRIPTION file of the R package allows to state the
order of ALL files (you can't write just the ones you want to load first)
* roxygen's `include` keyword (`#' @include first.R`)
* R's native function `source`
* Rename the files to be loaded (the ones to be loaded first should be first on
an alphanumeric sort)

The best one is using roxygen's `include` tag which will automatically order all
the packages in the DESCRIPTION file explicitely.

## Examples
Data used in examples need to be placed in a sensible place. If the data is 
going to be used by the user, it should go in the `data` folder; otherwise, it
should go to `inst/extdata`. It's recommended to only give RDS data to the user
since it's already processed and faster to load. Raw data in other formats like 
.txt and .csv (which should only be used in examples) should go to the folder
`inst/extdata`.

To use files stored in `inst/extdata`, it's needed to call them like this:
`system.file("extdata", "example.txt", package="psichomics")`, replacing
`example.txt` by the file of interest.

For more information, please see: http://r-pkgs.had.co.nz/data.html

# Software tools

## GitHub
GitHub is a service that hosts public and private Git repositories. Public 
repositories are free to any registered user while private ones are paid. 
However, students can create free unlimited private repositories.

There are also other Git repositories hosting services like Bitbucket but I
personally prefer the tools available in Github.

## Continuous integration
Travis CI (continuous integration) allows to to build and test software from 
GitHub repositories. By  using Travis CI, we're testing every modification of 
the project for errors. It officially supports a myriad of languages like 
Python, C++ and Java. Although it also supports R, its support is community
maintained. Travis CI for R uses `R CMD check` which will look for errors in the
documentation, comments, unit tests and the code itself. 

To enable Travis CI in a project, you simply need to create an account in Travis 
CI, turn the option on for the desired projects and insert a file named 
`.travis.yml` in the top level of the project. Now, everytime there's a new 
commit or a pull request, it will be automatically tested for errors, warnings
and notes.

Travis CI is available for free use for open-source GitHub projects. As a
student, not only GitHub allows me to store unlimited private repositories, I 
may also use Travis CI in private repositories for free. Anyway, as this project
will be soon open-source, there's no issue with using Travis CI in the long-term.

## Code coverage
Code coverage allows to quantify how much of the code is tested by unit tests.

To measure code coverage, I've decided to use Codecov (https://codecov.io) which
is free for the first private repository. To enable Codecov, you need to select 
the language used and the CI provider (in our case, it's R and Travis CI, 
respectively). This will give to the user a string which should be copied into
the `.travis.yml` file (general instructions are given here: 
https://github.com/codecov/example-r).

> TODO: check if methods with identical names from different classes are allowed

> TODO: change examples documentation (most are pre-vectorised versions)

> TODO: increase number of AFE and ALE events parsed

> TODO: validate if all events are of the same type (else, they are wrongly
parsed)... or better yet, parse all different event types (just using split
should be easy, no?)

> TODO: calculate inclusion levels from read counts for all event types

> TODO: save and restore Shiny session... else the page must NOT be reloaded! :(
Everything that depends on the global variable is still loaded (data loaded and 
data groups are intact, at least)

> TODO: use Travis CI in the project (only available for GitHub); more
information is available at http://r-pkgs.had.co.nz/check.html

> TODO: Pass R CMD build, R CMD check, and R CMD BiocCheck

> TODO: Remove "character(0)" warnings related to using NULL right below a
roxygen's @import

> TODO: Allow to choose visible columns in data tables

> TODO: Allow to search columns that are not visible in data tables

> TODO: Simplify format checkers... specially the virtual distinction between
ignoreRows and skip

> TODO: Add grep functionality when choosing groups

> TODO: (Un)check all checkboxes in the groups interface when (un)checking the
checkbox in the header

> TODO: Allow to use Firehose even if the server is down (for example, if we
only want to use the information we have already downloaded)

> TODO: Allow the user to choose the colors of the groups in the groups
interface

> TODO: Remove the warning messages when building the package. It happens 
because of different packages loading homonymic functions, so just load
the functions needed by each package.