# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

psiFastCalc <- function(mat, incA = 0L, incB = 0L, excA = 0L, excB = 0L, minReads = 10L) {
    .Call(`_psichomics_psiFastCalc`, mat, incA, incB, excA, excB, minReads)
}

psiFastCalc2 <- function(mat, inc, exc, minReads = 10L) {
    .Call(`_psichomics_psiFastCalc2`, mat, inc, exc, minReads)
}

discardVastToolsByCvg <- function(psi, eventData, qualityCol, scoresToDiscard) {
    .Call(`_psichomics_discardVastToolsByCvg`, psi, eventData, qualityCol, scoresToDiscard)
}

