# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

psiFastCalc <- function(mat, incA = 0L, incB = 0L, excA = 0L, excB = 0L, minReads = 10L) {
    .Call(`_psichomics_psiFastCalc`, mat, incA, incB, excA, excB, minReads)
}

